import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
import FirstComp from "../components/FirstComp";
import SecondComp from "../components/SecondComp";
import FinalComp from "../components/FinalComp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Space+Mono&display=swap');
        </style>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* <FirstComp /> */}
      <SecondComp />
      <FinalComp />
      home
    </div>
  );
}
